[package]
name = "kirkhoff_cross_ply"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "utils"
path = "src/lib.rs"

[dependencies]
nalgebra = "0.31.0"